### ISSUE TITLE
Allow passing a CLI argument to select sdist or bdist_wheel to avoid prompting

### ISSUE THREAD

**Issue by miketheman** [import-pandas-as-numpy/safepull#107]
If I wanted to script `safepull`, there's no way I can see right now to tell it to only pull the wheel instead of prompting.
`--force` will get the sdist always, but there's no inverse of that right now.

**Comment by import-pandas-as-numpy** [comment]
Based on my observations, wheels tend to occur in some quantity exceeding 1. 

Would the intended behavior here be to resolve the appropriate wheel for the current user's operating system, to obtain the first wheel found, or to obtain the wheel only if it's the only wheel present?

**Comment by miketheman** [comment]
That's an excellent question, I don't have a clear answer.

The purpose I've used it to download all of artifacts as part of an investigation, often for comparison to each other.

Considering that the tool knows how to extract wheels to their discrete named subdirectories, side by side, what if it downloaded all of the wheels?

**Comment by import-pandas-as-numpy** [comment]
Should be doable, I'll crunch on this and the other outstanding issue next week as I get some bandwidth. Don't think it'll take too long.
