### ISSUE TITLE
Add Black

### ISSUE THREAD

**Issue by import-pandas-as-numpy** [import-pandas-as-numpy/safepull#30]
- Forgot to add black for pre-commit, don't care to release a new version right now just to fix it.

**Comment by miketheman** [comment]
Should be resolved in https://github.com/import-pandas-as-numpy/safepull/pull/11/files#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9R13-R16

**Comment by import-pandas-as-numpy** [comment]
> Should be resolved in https://github.com/import-pandas-as-numpy/safepull/pull/11/files#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9R13-R16

Thanks @miketheman! Good looking out!
